# cm-13.0.yaml
#
# Crowdin configuration file for LineageOS
#
# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"api_token_env": LINEAGE_CROWDIN_API_TOKEN
"base_path_env": LINEAGE_CROWDIN_BASE_PATH_CM_13_0
"project_id": 237414
"preserve_hierarchy": true

"files": [
    {
        "source":      "/frameworks/base/core/res/res/values/cm_strings.xml",
        "translation": "/frameworks/base/core/res/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/frameworks/base/packages/Keyguard/res/values/cm_strings.xml",
        "translation": "/frameworks/base/packages/Keyguard/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/frameworks/base/packages/SettingsLib/res/values/cm_strings.xml",
        "translation": "/frameworks/base/packages/SettingsLib/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/frameworks/base/packages/SystemUI/res/values/cm_arrays.xml",
        "translation": "/frameworks/base/packages/SystemUI/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/frameworks/base/packages/SystemUI/res/values/cm_strings.xml",
        "translation": "/frameworks/base/packages/SystemUI/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/AudioFX/res/values/cm_strings.xml",
        "translation": "/packages/apps/AudioFX/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Bluetooth/res/values/cm_strings.xml",
        "translation": "/packages/apps/Bluetooth/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/BluetoothExt/res/values/strings.xml",
        "translation": "/packages/apps/BluetoothExt/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/BluetoothExt/res/values/strings_dun.xml",
        "translation": "/packages/apps/BluetoothExt/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/BluetoothExt/res/values/strings_ftp.xml",
        "translation": "/packages/apps/BluetoothExt/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/BluetoothExt/res/values/strings_map.xml",
        "translation": "/packages/apps/BluetoothExt/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/BluetoothExt/res/values/strings_sap.xml",
        "translation": "/packages/apps/BluetoothExt/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Browser/res/values/cm_strings.xml",
        "translation": "/packages/apps/Browser/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Calculator/res/values/cm_strings.xml",
        "translation": "/packages/apps/Calculator/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Calendar/res/values/cm_plurals.xml",
        "translation": "/packages/apps/Calendar/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Calendar/res/values/cm_strings.xml",
        "translation": "/packages/apps/Calendar/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Camera2/res/values/cm_strings.xml",
        "translation": "/packages/apps/Camera2/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/CellBroadcastReceiver/res/values/cm_strings.xml",
        "translation": "/packages/apps/CellBroadcastReceiver/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/CMBugReport/res/values/strings.xml",
        "translation": "/packages/apps/CMBugReport/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/CMFileManager/res/values/plurals.xml",
        "translation": "/packages/apps/CMFileManager/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/CMFileManager/res/values/strings.xml",
        "translation": "/packages/apps/CMFileManager/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/CMUpdater/res/values/plurals.xml",
        "translation": "/packages/apps/CMUpdater/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/CMUpdater/res/values/strings.xml",
        "translation": "/packages/apps/CMUpdater/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/CMWallpapers/res/values/strings.xml",
        "translation": "/packages/apps/CMWallpapers/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Contacts/res/values/cm_plurals.xml",
        "translation": "/packages/apps/Contacts/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Contacts/res/values/cm_strings.xml",
        "translation": "/packages/apps/Contacts/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/ContactsCommon/res/values/cm_plurals.xml",
        "translation": "/packages/apps/ContactsCommon/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/ContactsCommon/res/values/cm_strings.xml",
        "translation": "/packages/apps/ContactsCommon/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/DeskClock/res/values/cm_strings.xml",
        "translation": "/packages/apps/DeskClock/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Dialer/res/values/cm_arrays.xml",
        "translation": "/packages/apps/Dialer/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Dialer/res/values/cm_plurals.xml",
        "translation": "/packages/apps/Dialer/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Dialer/res/values/cm_strings.xml",
        "translation": "/packages/apps/Dialer/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Eleven/res/values/plurals.xml",
        "translation": "/packages/apps/Eleven/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Eleven/res/values/strings.xml",
        "translation": "/packages/apps/Eleven/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Email/res/values/cm_strings.xml",
        "translation": "/packages/apps/Email/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Gallery2/res/values/cm_strings.xml",
        "translation": "/packages/apps/Gallery2/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Gallery2/res/values/codeaurora_strings.xml",
        "translation": "/packages/apps/Gallery2/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Gello/res/raw/incognito_mode_start_page.html",
        "translation": "/packages/apps/Gello/res/raw-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Gello/res/values/strings.xml",
        "translation": "/packages/apps/Gello/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/InCallUI/res/values/cm_strings.xml",
        "translation": "/packages/apps/InCallUI/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/InCallUI/res/values/qtistrings.xml",
        "translation": "/packages/apps/InCallUI/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/LockClock/res/values/strings.xml",
        "translation": "/packages/apps/LockClock/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Messaging/res/values/cm_strings.xml",
        "translation": "/packages/apps/Messaging/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/PhoneCommon/res/values/cm_strings.xml",
        "translation": "/packages/apps/PhoneCommon/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Profiles/res/values/strings.xml",
        "translation": "/packages/apps/Profiles/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Screencast/res/values/strings.xml",
        "translation": "/packages/apps/Screencast/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Settings/res/values/cm_plurals.xml",
        "translation": "/packages/apps/Settings/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Settings/res/values/cm_strings.xml",
        "translation": "/packages/apps/Settings/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/SetupWizard/res/values/strings.xml",
        "translation": "/packages/apps/SetupWizard/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Snap/res/values/cm_strings.xml",
        "translation": "/packages/apps/Snap/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Snap/res/values/qcomstrings.xml",
        "translation": "/packages/apps/Snap/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Snap/res/values/strings.xml",
        "translation": "/packages/apps/Snap/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/SoundRecorder/res/values/cm_strings.xml",
        "translation": "/packages/apps/SoundRecorder/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Stk/res/values/cm_strings.xml",
        "translation": "/packages/apps/Stk/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Terminal/res/values/arrays.xml",
        "translation": "/packages/apps/Terminal/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Terminal/res/values/strings.xml",
        "translation": "/packages/apps/Terminal/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/ThemeChooser/res/values/strings.xml",
        "translation": "/packages/apps/ThemeChooser/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Trebuchet/res/values/cm_arrays.xml",
        "translation": "/packages/apps/Trebuchet/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Trebuchet/res/values/cm_strings.xml",
        "translation": "/packages/apps/Trebuchet/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/TvSettings/Settings/res/values/cm_strings.xml",
        "translation": "/packages/apps/TvSettings/Settings/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/UnifiedEmail/res/values/cm_strings.xml",
        "translation": "/packages/apps/UnifiedEmail/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/inputmethods/LatinIME/java/res/values/cm_strings.xml",
        "translation": "/packages/inputmethods/LatinIME/java/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/providers/DataUsageProvider/res/values/strings.xml",
        "translation": "/packages/providers/DataUsageProvider/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/providers/DownloadProvider/res/values/cm_plurals.xml",
        "translation": "/packages/providers/DownloadProvider/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/providers/DownloadProvider/res/values/cm_strings.xml",
        "translation": "/packages/providers/DownloadProvider/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/providers/ThemesProvider/res/values/strings.xml",
        "translation": "/packages/providers/ThemesProvider/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/providers/WeatherProvider/res/values/strings.xml",
        "translation": "/packages/providers/WeatherProvider/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/screensavers/PhotoTable/res/values/cm_strings.xml",
        "translation": "/packages/screensavers/PhotoTable/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/services/CMAudioService/res/values/strings.xml",
        "translation": "/packages/services/CMAudioService/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/services/LiveLockScreenService/res/values/strings.xml",
        "translation": "/packages/services/LiveLockScreenService/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/services/Mms/res/values/cm_strings.xml",
        "translation": "/packages/services/Mms/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/services/Telecomm/res/values/cm_strings.xml",
        "translation": "/packages/services/Telecomm/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/services/Telephony/res/values/cm_strings.xml",
        "translation": "/packages/services/Telephony/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/services/Telephony/res/values/qtistrings.xml",
        "translation": "/packages/services/Telephony/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/services/ThemeManagerService/res/values/strings.xml",
        "translation": "/packages/services/ThemeManagerService/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/services/WeatherService/res/values/strings.xml",
        "translation": "/packages/services/WeatherService/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/wallpapers/Galaxy4/res/values/strings.xml",
        "translation": "/packages/wallpapers/Galaxy4/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/wallpapers/PhaseBeam/res/values/cm_strings.xml",
        "translation": "/packages/wallpapers/PhaseBeam/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/wallpapers/PhotoPhase/res/values/plurals.xml",
        "translation": "/packages/wallpapers/PhotoPhase/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/wallpapers/PhotoPhase/res/values/strings.xml",
        "translation": "/packages/wallpapers/PhotoPhase/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/vendor/cmsdk/cm/res/res/values/strings.xml",
        "translation": "/vendor/cmsdk/cm/res/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/vendor/cmsdk/packages/CMSettingsProvider/res/values/strings.xml",
        "translation": "/vendor/cmsdk/packages/CMSettingsProvider/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/vendor/cmsdk/samples/weatherproviderservice/OpenWeatherMapProvider/app/src/main/res/values/strings.xml",
        "translation": "/vendor/cmsdk/samples/weatherproviderservice/OpenWeatherMapProvider/app/src/main/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/hardware/qcom/fm/fmapp2/res/values/arrays.xml",
        "translation": "/hardware/qcom/fm/fmapp2/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/hardware/qcom/fm/fmapp2/res/values/strings.xml",
        "translation": "/hardware/qcom/fm/fmapp2/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/hardware/qcom/fm/FMRecord/res/values/strings.xml",
        "translation": "/hardware/qcom/fm/FMRecord/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/SamsungServiceMode/res/values/strings.xml",
        "translation": "/packages/apps/SamsungServiceMode/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/device/samsung/qcom-common/doze/res/values/strings.xml",
        "translation": "/device/samsung/qcom-common/doze/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/hardware/samsung/AdvancedDisplay/res/values/arrays.xml",
        "translation": "/hardware/samsung/AdvancedDisplay/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/hardware/samsung/AdvancedDisplay/res/values/strings.xml",
        "translation": "/hardware/samsung/AdvancedDisplay/res/values-%android_code%/%original_file_name%"
    }
]
