# cm-13.0_aosp.yaml
#
# Crowdin configuration file for LineageOS'
# additional languages not supported by AOSP
#
# Copyright (C) 2014-2015 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api_key_env: CM_AOSP_CROWDIN_API_KEY
base_path_env: CM_CROWDIN_BASE_PATH
base_path_contains_branch_subfolders: true
project_identifier: lineageos-aosp
preserve_hierarchy: true

files:
# Frameworks

  # framework-res
  -
    source:      '/frameworks/base/core/res/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: &anchor
      android_code:
        as: as-rIN
        ast: ast-rES
        be: be
        cy: cy
        en-PT: en-rPT
        es-MX: es-rMX
        eo: eo
        fy-NL: fy-rNL
        kab: kab-rDZ
        ku: ku
        lb: lb
        or: or-rIN
        sc: sc-rIT
        ug: ug

  # BackupRestoreConfirmation
  -
    source:      '/frameworks/base/packages/BackupRestoreConfirmation/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # CaptivePortalLogin
  -
    source:      '/frameworks/base/packages/CaptivePortalLogin/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # DefaultContainerService
  -
    source:      '/frameworks/base/packages/DefaultContainerService/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # DocumentsUI
  -
    source:      '/frameworks/base/packages/DocumentsUI/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # ExternalStorageProvider
  -
    source:      '/frameworks/base/packages/ExternalStorageProvider/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # FusedLocation
  -
    source:      '/frameworks/base/packages/FusedLocation/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # InputDevices
  -
    source:      '/frameworks/base/packages/InputDevices/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Keyguard
  -
    source:      '/frameworks/base/packages/Keyguard/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # PrintSpooler
  -
    source:      '/frameworks/base/packages/PrintSpooler/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # SettingsLib
  -
    source:      '/frameworks/base/packages/SettingsLib/res/values/arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/frameworks/base/packages/SettingsLib/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # SettingsProvider
  -
    source:      '/frameworks/base/packages/SettingsProvider/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Shell
  -
    source:      '/frameworks/base/packages/Shell/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # StatementService
  -
    source:      '/frameworks/base/packages/StatementService/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # SystemUI
  -
    source:      '/frameworks/base/packages/SystemUI/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # VpnDialogs
  -
    source:      '/frameworks/base/packages/VpnDialogs/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # WallpaperCropper
  -
    source:      '/frameworks/base/packages/WallpaperCropper/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Packages

  # AudioFX
  -
    source:      '/packages/apps/AudioFX/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # BasicSmsReceiver
  -
    source:      '/packages/apps/BasicSmsReceiver/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Bluetooth
  -
    source:      '/packages/apps/Bluetooth/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Bluetooth/res/values/strings_pbap.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Bluetooth/res/values/strings_sap.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Browser
  -
    source:      '/packages/apps/Browser/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Calendar
  -
    source:      '/packages/apps/Calendar/res/values/arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Calendar/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Camera2
  -
    source:      '/packages/apps/Camera2/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Camera2/res_p/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # CellBroadcastReceiver
  -
    source:      '/packages/apps/CellBroadcastReceiver/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # CertInstaller
  -
    source:      '/packages/apps/CertInstaller/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Contacts
  -
    source:      '/packages/apps/Contacts/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # ContactsCommon
  -
    source:      '/packages/apps/ContactsCommon/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # DeskClock
  -
    source:      '/packages/apps/DeskClock/res/values/array.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/DeskClock/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Dialer
  -
    source:      '/packages/apps/Dialer/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Email
  -
    source:      '/packages/apps/Email/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # ExactCalculator
  -
    source:      '/packages/apps/ExactCalculator/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Exchange
  -
    source:      '/packages/apps/Exchange/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # FMRadio
  -
    source:      '/packages/apps/FMRadio/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Gallery2
  -
    source:      '/packages/apps/Gallery2/res/values/filtershow_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Gallery2/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # HTMLViewer
  -
    source:      '/packages/apps/HTMLViewer/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # InCallUI
  -
    source:      '/packages/apps/InCallUI/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # KeyChain
  -
    source:      '/packages/apps/KeyChain/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # ManagedProvisioning
  -
    source:      '/packages/apps/ManagedProvisioning/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Messaging
  -
    source:      '/packages/apps/Messaging/res/values/arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Messaging/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Nfc
  -
    source:      '/packages/apps/Nfc/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # PackageInstaller
  -
    source:      '/packages/apps/PackageInstaller/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # PhoneCommon
  -
    source:      '/packages/apps/PhoneCommon/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Settings
  -
    source:      '/packages/apps/Settings/res/values/arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Settings/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # SoundRecorder
  -
    source:      '/packages/apps/SoundRecorder/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Stk
  -
    source:      '/packages/apps/Stk/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Tag
  -
    source:      '/packages/apps/Tag/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Trebuchet
  -
    source:      '/packages/apps/Trebuchet/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # TvSettings
  -
    source:      '/packages/apps/TvSettings/Settings/res/values/arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/TvSettings/Settings/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # UnifiedEmail
  -
    source:      '/packages/apps/UnifiedEmail/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # WallpaperPicker
  -
    source:      '/packages/apps/WallpaperPicker/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Input methods

  # LatinIME
  -
    source:      '/packages/inputmethods/LatinIME/java/res/values/strings-action-keys.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/inputmethods/LatinIME/java/res/values/strings-appname.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/inputmethods/LatinIME/java/res/values/strings-config-important-notice.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/inputmethods/LatinIME/java/res/values/strings-emoji-descriptions.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/inputmethods/LatinIME/java/res/values/strings-letter-descriptions.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/inputmethods/LatinIME/java/res/values/strings-talkback-descriptions.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/inputmethods/LatinIME/java/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Providers

  # BookmarkProvider
  -
    source:      '/packages/providers/BookmarkProvider/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # CalendarProvider
  -
    source:      '/packages/providers/CalendarProvider/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # CallLogProvider
  -
    source:      '/packages/providers/CallLogProvider/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # ContactsProvider
  -
    source:      '/packages/providers/ContactsProvider/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # DownloadProvider
  -
    source:      '/packages/providers/DownloadProvider/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/providers/DownloadProvider/ui/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # MediaProvider
  -
    source:      '/packages/providers/MediaProvider/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # TelephonyProvider
  -
    source:      '/packages/providers/TelephonyProvider/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # UserDictionaryProvider
  -
    source:      '/packages/providers/UserDictionaryProvider/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Screensavers

  # Basic
  -
    source:      '/packages/screensavers/Basic/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # PhotoTable
  -
    source:      '/packages/screensavers/PhotoTable/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Services

  # Telecomm
  -
    source:      '/packages/services/Telecomm/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Telephony
  -
    source:      '/packages/services/Telephony/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/services/Telephony/sip/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Wallpapers

  # Basic
  -
    source:      '/packages/wallpapers/Basic/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # HoloSpiral
  -
    source:      '/packages/wallpapers/HoloSpiral/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # LivePicker
  -
    source:      '/packages/wallpapers/LivePicker/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # MagicSmoke
  -
    source:      '/packages/wallpapers/MagicSmoke/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # NoiseField
  -
    source:      '/packages/wallpapers/NoiseField/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # PhaseBeam
  -
    source:      '/packages/wallpapers/PhaseBeam/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
