# cm-14.1.yaml
#
# Crowdin configuration file for LineageOS
#
# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"api_token_env": LINEAGE_CROWDIN_API_TOKEN,
"base_path_env": LINEAGE_CROWDIN_BASE_PATH_CM_14_1,
"project_id": 237414,
"preserve_hierarchy": true,

"files": [
    {
        "source":      "/frameworks/base/core/res/res/values/cm_strings.xml",
        "translation": "/frameworks/base/core/res/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/frameworks/base/packages/SettingsLib/res/values/cm_strings.xml",
        "translation": "/frameworks/base/packages/SettingsLib/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/frameworks/base/packages/SystemUI/res/values/cm_strings.xml",
        "translation": "/frameworks/base/packages/SystemUI/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/AudioFX/res/values/cm_strings.xml",
        "translation": "/packages/apps/AudioFX/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Bluetooth/res/values/cm_strings.xml",
        "translation": "/packages/apps/Bluetooth/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Calendar/res/values/cm_plurals.xml",
        "translation": "/packages/apps/Calendar/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Calendar/res/values/cm_strings.xml",
        "translation": "/packages/apps/Calendar/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Camera2/res/values/cm_strings.xml",
        "translation": "/packages/apps/Camera2/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/CellBroadcastReceiver/res/values/cm_strings.xml",
        "translation": "/packages/apps/CellBroadcastReceiver/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/CMParts/res/values/plurals.xml",
        "translation": "/packages/apps/CMParts/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/CMParts/res/values/strings.xml",
        "translation": "/packages/apps/CMParts/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Contacts/res/values/cm_strings.xml",
        "translation": "/packages/apps/Contacts/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/ContactsCommon/res/values/cm_strings.xml",
        "translation": "/packages/apps/ContactsCommon/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/DeskClock/res/values/cm_strings.xml",
        "translation": "/packages/apps/DeskClock/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Dialer/res/values/cm_arrays.xml",
        "translation": "/packages/apps/Dialer/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Dialer/res/values/cm_plurals.xml",
        "translation": "/packages/apps/Dialer/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Dialer/res/values/cm_strings.xml",
        "translation": "/packages/apps/Dialer/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Dialer/InCallUI/res/values/cm_strings.xml",
        "translation": "/packages/apps/Dialer/InCallUI/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Dialer/InCallUI/res/values/qtistrings.xml",
        "translation": "/packages/apps/Dialer/InCallUI/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Eleven/res/values/plurals.xml",
        "translation": "/packages/apps/Eleven/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Eleven/res/values/strings.xml",
        "translation": "/packages/apps/Eleven/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Email/res/values/cm_strings.xml",
        "translation": "/packages/apps/Email/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/FMRadio/res/values/cm_strings.xml",
        "translation": "/packages/apps/FMRadio/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Gallery2/res/values/cm_strings.xml",
        "translation": "/packages/apps/Gallery2/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Gallery2/res/values/codeaurora_strings.xml",
        "translation": "/packages/apps/Gallery2/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Jelly/app/src/main/res/values/strings.xml",
        "translation": "/packages/apps/Jelly/app/src/main/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/LockClock/res/values/strings.xml",
        "translation": "/packages/apps/LockClock/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Messaging/res/values/cm_strings.xml",
        "translation": "/packages/apps/Messaging/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/PhoneCommon/res/values/qtistrings.xml",
        "translation": "/packages/apps/PhoneCommon/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Profiles/res/values/strings.xml",
        "translation": "/packages/apps/Profiles/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Recorder/app/src/main/res/values/strings.xml",
        "translation": "/packages/apps/Recorder/app/src/main/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Settings/res/values/cm_plurals.xml",
        "translation": "/packages/apps/Settings/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Settings/res/values/cm_strings.xml",
        "translation": "/packages/apps/Settings/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/SetupWizard/res/values/strings.xml",
        "translation": "/packages/apps/SetupWizard/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Snap/res/values/cm_strings.xml",
        "translation": "/packages/apps/Snap/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Snap/res/values/qcomstrings.xml",
        "translation": "/packages/apps/Snap/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Snap/res/values/strings.xml",
        "translation": "/packages/apps/Snap/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Snap/quickReader/res/values/strings.xml",
        "translation": "/packages/apps/Snap/quickReader/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Terminal/res/values/arrays.xml",
        "translation": "/packages/apps/Terminal/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Terminal/res/values/strings.xml",
        "translation": "/packages/apps/Terminal/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Trebuchet/res/values/cm_arrays.xml",
        "translation": "/packages/apps/Trebuchet/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Trebuchet/res/values/cm_strings.xml",
        "translation": "/packages/apps/Trebuchet/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/UnifiedEmail/res/values/cm_strings.xml",
        "translation": "/packages/apps/UnifiedEmail/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/Updater/res/values/strings.xml",
        "translation": "/packages/apps/Updater/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/WallpaperPicker/res/values/cm_strings.xml",
        "translation": "/packages/apps/WallpaperPicker/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/inputmethods/LatinIME/java/res/values/cm_strings.xml",
        "translation": "/packages/inputmethods/LatinIME/java/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/providers/DataUsageProvider/res/values/strings.xml",
        "translation": "/packages/providers/DataUsageProvider/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/providers/DownloadProvider/res/values/cm_plurals.xml",
        "translation": "/packages/providers/DownloadProvider/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/providers/DownloadProvider/res/values/cm_strings.xml",
        "translation": "/packages/providers/DownloadProvider/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/providers/WeatherProvider/res/values/strings.xml",
        "translation": "/packages/providers/WeatherProvider/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/services/CMAudioService/res/values/strings.xml",
        "translation": "/packages/services/CMAudioService/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/services/Telephony/res/values/cm_strings.xml",
        "translation": "/packages/services/Telephony/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/services/Telephony/res/values/qtistrings.xml",
        "translation": "/packages/services/Telephony/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/services/WeatherService/res/values/strings.xml",
        "translation": "/packages/services/WeatherService/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/vendor/cmsdk/cm/res/res/values/strings.xml",
        "translation": "/vendor/cmsdk/cm/res/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/vendor/cmsdk/packages/CMSettingsProvider/res/values/strings.xml",
        "translation": "/vendor/cmsdk/packages/CMSettingsProvider/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/vendor/cmsdk/samples/weatherproviderservice/OpenWeatherMapProvider/app/src/main/res/values/strings.xml",
        "translation": "/vendor/cmsdk/samples/weatherproviderservice/OpenWeatherMapProvider/app/src/main/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/hardware/qcom/fm/fmapp2/res/values/arrays.xml",
        "translation": "/hardware/qcom/fm/fmapp2/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/hardware/qcom/fm/fmapp2/res/values/strings.xml",
        "translation": "/hardware/qcom/fm/fmapp2/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/hardware/qcom/fm/FMRecord/res/values/strings.xml",
        "translation": "/hardware/qcom/fm/FMRecord/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/SamsungServiceMode/res/values/strings.xml",
        "translation": "/packages/apps/SamsungServiceMode/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/device/oppo/common/configpanel/res/values/strings.xml",
        "translation": "/device/oppo/common/configpanel/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/device/sony/huashan/devicesettings/res/values/strings.xml",
        "translation": "/device/sony/huashan/devicesettings/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/hardware/samsung/AdvancedDisplay/res/values/arrays.xml",
        "translation": "/hardware/samsung/AdvancedDisplay/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/hardware/samsung/AdvancedDisplay/res/values/strings.xml",
        "translation": "/hardware/samsung/AdvancedDisplay/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/resources/devicesettings/res/values/strings.xml",
        "translation": "/packages/resources/devicesettings/res/values-%android_code%/%original_file_name%"
    },
    {
        "source":      "/packages/apps/FlipFlap/res/values/strings.xml",
        "translation": "/packages/apps/FlipFlap/res/values-%android_code%/%original_file_name%"
    }
]
