# lineage-15.1.yaml
#
# Crowdin configuration file for LineageOS
#
# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api_key_env: CM_CROWDIN_API_KEY
base_path_env: CM_CROWDIN_BASE_PATH
base_path_contains_branch_subfolders: true
project_identifier: lineageos
preserve_hierarchy: true

files:
# Frameworks

  # framework-res
  -
    source:      '/frameworks/base/core/res/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: &anchor
      android_code:
        # Afrikaans
        af: af
        # Albanian
        sq: sq
        # Amharic
        am: am
        # Arabic
        ar: ar
        # Armenian
        hy-AM: hy
        # Arpitan - LineageOS
        frp: frp
        # Assamese - LineageOS
        as: as-rIN
        # Asturian - LineageOS
        ast: ast-rES
        # Azerbaijani
        az: az
        # Basque
        eu: eu
        # Belarusian
        be: be
        # Bengali
        bn: bn
        # Bosnian
        bs: bs
        # Breton - LineageOS
        br-FR: br-rFR
        # Bulgarian
        bg: bg
        # Burmese
        my: my
        # Catalan
        ca: ca
        # Chinese Simplified
        zh-CN: zh-rCN
        # Chinese Traditional
        zh-TW: zh-rTW
        # Chinese Traditional, Hong Kong
        zh-HK: zh-rHK
        # Croatian
        hr: hr
        # Czech
        cs: cs
        # Danish
        da: da
        # Dutch
        nl: nl
        # English, Australia
        en-AU: en-rAU
        # English, Canada
        en-CA: en-rCA
        # English, India
        en-IN: en-rIN
        # English, United Kingdom
        en-GB: en-rGB
        # Esperanto - LineageOS
        eo: eo
        # Estonian
        et: et
        # Filipino - LineageOS
        fil: fil
        # Finnish
        fi: fi
        # French
        fr: fr
        # French, Canada
        fr-CA: fr-rCA
        # Frisian - LineageOS
        fy-NL: fy-rNL
        # Galician
        gl: gl
        # Georgian
        ka: ka
        # German
        de: de
        # Greek
        el: el
        # Gujarati
        gu-IN: gu
        # Hebrew
        he: iw
        # Hindi
        hi: hi
        # Hungarian
        hu: hu
        # Icelandic
        is: is
        # Indonesian
        id: in
        # Irish - LineageOS
        ga-IE: ga-rIE
        # Italian
        it: it
        # Japanese
        ja: ja
        # Kabyle - LineageOS
        kab: kab-rDZ
        # Kannada
        kn: kn
        # Kashubian - LineageOS
        csb: csb
        # Kazakh
        kk: kk
        # Khmer
        km: km
        # Korean
        ko: ko
        # Kurdish - LineageOS
        ku: ku
        # Kyrgyz
        ky: ky
        # Lao
        lo: lo
        # Latvian
        lv: lv
        # Lithuanian
        lt: lt
        # Luxembourgish - LineageOS
        lb: lb
        # Macedonian (FYROM)
        mk: mk
        # Malay
        ms: ms
        # Malayalam
        ml-IN: ml
        # Marathi
        mr: mr
        # Mongolian
        mn: mn
        # Nepali
        ne-NP: ne
        # Norwegian Bokmal
        nb: nb
        # Occitan - LineageOS
        oc: oc
        # Oriya - LineageOS
        or: or-rIN
        # Persian
        fa: fa
        # Pirate English - LineageOS
        en-PT: en-rPT
        # Polish
        pl: pl
        # Portuguese
        pt-PT: pt-rPT
        # Portuguese, Brazilian
        pt-BR: pt-rBR
        # Punjabi
        pa-IN: pa
        # Romanian
        ro: ro
        # Romansh - LineageOS
        rm-CH: rm
        # Russian
        ru: ru
        # Sardinian - LineageOS
        sc: sc-rIT
        # Scottish Gaelic - LineageOS
        gd: gd
        # Serbian (Cyrillic)
        sr: sr
        # Serbian (Latin)
        sr-CS: b+sr+Latn
        # Sinhala
        si-LK: si
        # Slovak
        sk: sk
        # Slovenian
        sl: sl
        # Spanish
        es-ES: es
        # Spanish, Colombia - LineageOS
        es-CO: es-rCO
        # Spanish, Mexico - LineageOS
        es-MX: es-rMX
        # Spanish, United States
        es-US: es-rUS
        # Swahili
        sw: sw
        # Swedish
        sv-SE: sv
        # Tagalog
        tl: tl
        # Tamil
        ta: ta
        # Telugu
        te: te
        # Thai
        th: th
        # Turkish
        tr: tr
        # Ukrainian
        uk: uk
        # Urdu (Pakistan)
        ur-PK: ur
        # Uyghur - LineageOS
        ug: ug
        # Uzbek
        uz: uz
        # Venetian - LineageOS
        vec: vec
        # Vietnamese
        vi: vi
        # Welsh - LineageOS
        cy: cy
        # Zulu
        zu: zu

  # SettingsLib
  -
    source:      '/frameworks/base/packages/SettingsLib/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # SystemUI
  -
    source:      '/frameworks/base/packages/SystemUI/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Packages

  # AudioFX
  -
    source:      '/packages/apps/AudioFX/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Camera2
  -
    source:      '/packages/apps/Camera2/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Contacts
  -
    source:      '/packages/apps/Contacts/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # DeskClock
  -
    source:      '/packages/apps/DeskClock/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Dialer
  -
    source:      '/packages/apps/Dialer/java/com/android/dialer/app/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Dialer/java/com/android/dialer/calldetails/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Dialer/java/com/android/dialer/calllogutils/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Dialer/java/com/android/dialer/callstats/res/values/cm_arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Dialer/java/com/android/dialer/callstats/res/values/cm_plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Dialer/java/com/android/dialer/callstats/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Dialer/java/com/android/dialer/contactgrid/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Dialer/java/com/android/dialer/lookup/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Dialer/java/com/android/incallui/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Eleven
  -
    source:      '/packages/apps/Eleven/res/values/plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Eleven/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Email
  -
    source:      '/packages/apps/Email/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # FMRadio
  -
    source:      '/packages/apps/FMRadio/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/FMRadio/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Gallery2
  -
    source:      '/packages/apps/Gallery2/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Gallery2/res/values/codeaurora_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Jelly
  -
    source:      '/packages/apps/Jelly/app/src/main/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # LineageParts
  -
    source:      '/packages/apps/LineageParts/res/values/plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/LineageParts/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # LockClock
  -
    source:      '/packages/apps/LockClock/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Messaging
  -
    source:      '/packages/apps/Messaging/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Profiles
  -
    source:      '/packages/apps/Profiles/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Recorder
  -
    source:      '/packages/apps/Recorder/app/src/main/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Settings
  -
    source:      '/packages/apps/Settings/res/values/cm_plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Settings/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # SetupWizard
  -
    source:      '/packages/apps/SetupWizard/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Snap
  -
    source:      '/packages/apps/Snap/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Snap/res/values/qcomstrings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Snap/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Snap/quickReader/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Terminal
  -
    source:      '/packages/apps/Terminal/res/values/arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Terminal/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Trebuchet
  -
    source:      '/packages/apps/Trebuchet/res/values/lineage_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # UnifiedEmail
  -
    source:      '/packages/apps/UnifiedEmail/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Updater
  -
    source:      '/packages/apps/Updater/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # WallpaperPicker
  -
    source:      '/packages/apps/WallpaperPicker/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Input methods

  # LatinIME
  -
    source:      '/packages/inputmethods/LatinIME/java/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Providers

  # DownloadProvider
  -
    source:      '/packages/providers/DownloadProvider/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # WeatherProvider
  -
    source:      '/packages/providers/WeatherProvider/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Services

  # Mms
  -
    source:      '/packages/services/Mms/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Telephony
  -
    source:      '/packages/services/Telephony/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Lineage SDK

  # Lineage SDK
  -
    source:      '/lineage-sdk/lineage/res/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # LineageSettingsProvider
  -
    source:      '/lineage-sdk/packages/LineageSettingsProvider/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # OpenWeatherMapProvider
  -
    source:      '/lineage-sdk/samples/weatherproviderservice/OpenWeatherMapProvider/app/src/main/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # WundergroundWeatherProvider
  -
    source:      '/lineage-sdk/samples/weatherproviderservice/WundergroundWeatherProvider/app/src/main/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # YahooWeatherProvider
  -
    source:      '/lineage-sdk/samples/weatherproviderservice/YahooWeatherProvider/app/src/main/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Device specific

  # fmapp2
  -
    source:      '/hardware/qcom/fm/fmapp2/res/values/arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/hardware/qcom/fm/fmapp2/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # FMRecord
  -
    source:      '/hardware/qcom/fm/FMRecord/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # oppo common configpanel
  -
    source:      '/device/oppo/common/configpanel/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # oppo r5 otgtoggle
  -
    source:      '/device/oppo/r5/otgtoggle/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # samsung AdvancedDisplay
  -
    source:      '/hardware/samsung/AdvancedDisplay/res/values/arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/hardware/samsung/AdvancedDisplay/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # resources devicesettings
  -
    source:      '/packages/resources/devicesettings/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # FlipFlap
  -
    source:      '/packages/apps/FlipFlap/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
